# Generated by Django 4.1.6 on 2023-04-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='model_employee',
            name='phone',
            field=models.IntegerField(blank=True, default=91, null=True),
        ),
    ]
