# Generated by Django 4.1.6 on 2023-04-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_model_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_employee',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='model_employee',
            name='phone',
            field=models.IntegerField(default=91),
        ),
    ]
